### ISSUE TITLE
serve_run.py无法运行

### ISSUE THREAD

**Issue by Pattie1995** [zepen/lstm_pos#1]
-----------------------------------------------------------------------------------------------------
[INFO] The vocab_dict is load!
[INFO] The label_dict is load!
[INFO] The num_dict is load!
WARNING:tensorflow:From F:\Program Files (x86)\python3.6\00\lib\site-packages\keras\backend\tensorflow_backend.py:1247: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
[INFO] The Lstm model is load
-----------------------------------------------------------------------------------------------------
到这步之后就不动了，请问一下是程序出现了什么问题吗？

**Comment by zepen** [comment]
服务启动了呀，在网页端访问直接访问就好了。

**Comment by Pattie1995** [comment]
您好，这个是我运行serve_run.py后的结果：
=======================================================
Connected to pydev debugger (build 191.6605.12)
 * Serving Flask app "serve_run.py"
 * Environment: development
 * Debug mode: off
Using TensorFlow backend.
[INFO] The vocab_dict is load!
[INFO] The label_dict is load!
[INFO] The num_dict is load!
WARNING:tensorflow:From F:\Program Files (x86)\python3.6\00\lib\site-packages\keras\backend\tensorflow_backend.py:1247: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
[INFO] The Lstm model is load!
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
============================================================
我想问一下在网页端是访问哪一个网站呢？如果是predict_message_test.html的话，里面输入文字之后没有反应；如果是http://127.0.0.1:5000/，只显示了welcome to use!
希望得到解答，谢谢！

**Comment by zepen** [comment]
试试 http://127.0.0.1:5000/cut_word_views   
可以打开一个界面，直接粘贴要分词的文本进去就可以了。抱歉我没有在文档中说明。以后会考虑把它设计成package，可以pip install
